name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main  # Le pipeline sera déclenché lorsqu'il y a un push sur la branche main
  pull_request:
    branches:
      - main  # Il sera aussi déclenché lorsqu'un pull request est créé vers la branche main

jobs:
  build:
    runs-on: ubuntu-latest  # Le pipeline s'exécute sur une machine virtuelle Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Cette étape permet de récupérer le code du repository

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Définir la version de Node.js à utiliser

    - name: Install dependencies
      run: npm install  # Installation des dépendances avec npm

    - name: Run tests
      run: npm test  # Exécution des tests

    - name: Deploy to production
      run: |
        if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
          # Ajouter ici la commande pour déployer ton application en production
          echo "Déploiement sur la production"
        fi
